// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WpfTest.Context;

namespace WpfTest.Migrations
{
    [DbContext(typeof(TableDB))]
    [Migration("20211106231236_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WpfTest.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("x10")
                        .HasColumnType("text");

                    b.Property<string>("x11")
                        .HasColumnType("text");

                    b.Property<string>("x12")
                        .HasColumnType("text");

                    b.Property<string>("x13")
                        .HasColumnType("text");

                    b.Property<string>("x14")
                        .HasColumnType("text");

                    b.Property<string>("x1a")
                        .HasColumnType("text");

                    b.Property<string>("x1b")
                        .HasColumnType("text");

                    b.Property<string>("x1c")
                        .HasColumnType("text");

                    b.Property<string>("x1d")
                        .HasColumnType("text");

                    b.Property<string>("x2")
                        .HasColumnType("text");

                    b.Property<string>("x3")
                        .HasColumnType("text");

                    b.Property<string>("x4")
                        .HasColumnType("text");

                    b.Property<string>("x5")
                        .HasColumnType("text");

                    b.Property<string>("x6")
                        .HasColumnType("text");

                    b.Property<string>("x7")
                        .HasColumnType("text");

                    b.Property<string>("x8")
                        .HasColumnType("text");

                    b.Property<string>("x9")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
